name = "mydashboard"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# For production: replace with your D1 database_id from "wrangler d1 create"
[[d1_databases]]
binding = "DB"
database_name = "milk-hissab-db"
database_id = "df8a12dd-6c04-4a79-8444-34756ccf077f"